spring:
  application:
    name: spring-batch-parallel
  datasource:
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

job:
  input-data-dir: "goodbooks-10k/books.csv"
  chunk-size: 1000

lucene:
  index-dir: "index"
  config:
    ram-buffer: 256.0
    open-mode: CREATE_OR_APPEND
    enable-compound-file: false